name: publish
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'yarn'
      - run: yarn install
      - name: building core
      - run: yarn test:core
      - run: yarn build:core
      - uses: actions/upload-artifact@v2
        with:
          name: core-package
          path: dist/core
          if-no-files: error

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: actions/download-artifact@v2
        with:
          name: core-package
          path: dist/core
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${ secrets.NPM_TOKEN }
          package: dist/core/package.json
          access: public
